// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/user.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	v1 "example-nunu/api/v1"
	gomock "github.com/golang/mock/gomock"
)

// MockTqAppService is a mock of AppService interface.
type MockTqAppService struct {
	ctrl     *gomock.Controller
	recorder *MockTqAppServiceMockRecorder
}

// MockTqAppServiceMockRecorder is the mock recorder for MockTqAppService.
type MockTqAppServiceMockRecorder struct {
	mock *MockTqAppService
}

// NewMockTqAppService creates a new mock instance.
func NewMockTqAppService(ctrl *gomock.Controller) *MockTqAppService {
	mock := &MockTqAppService{ctrl: ctrl}
	mock.recorder = &MockTqAppServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTqAppService) EXPECT() *MockTqAppServiceMockRecorder {
	return m.recorder
}

// TqAppIndex mocks base method.
func (m *MockTqAppService) TqAppIndex(ctx context.Context) (*v1.AppIndex, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TqAppIndex", ctx)
	ret0, _ := ret[0].(*v1.AppIndex)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TqAppIndex indicates an expected call of TqAppIndex.
func (mr *MockTqAppServiceMockRecorder) TqAppIndex(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TqAppIndex", reflect.TypeOf((*MockTqAppService)(nil).TqAppIndex), ctx)
}
